stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - npm install
    - npm run build

test_job:
  stage: test
  script:
    - echo "Add test job here"

deploy_job:
  stage: deploy
  script:
    - echo "Add deploy job here"
